# Configuration assessment
# CIS Checks for Windows applications
# Copyright (C) 2015-2019, Wazuh Inc.
#
# This program is a free software; you can redistribute it
# and/or modify it under the terms of the GNU General Public
# License (version 2) as published by the FSF - Free Software
# Foundation
#

policy:
  id: "win_applications"
  file: "win_applications_rcl.yml"
  name: "Benchmark for Windows applications"
  description: "This document provides prescriptive guidance for establishing a secure configuration posture for Windows systems."
  references:
    - https://www.cisecurity.org/cis-benchmarks/

checks:
 - id: 10000
   title: "Chat/IM/VoIP - Skype"
   compliance:
    - pci_dss: "10.6.1"
   condition: any
   rules:
     - 'f:\Program Files\Skype\Phone;'
     - 'f:\Documents and Settings\All Users\Documents\My Skype Pictures;'
     - 'f:\Documents and Settings\Skype;'
     - 'f:\Documents and Settings\All Users\Start Menu\Programs\Skype;'
     - 'r:HKLM\SOFTWARE\Skype;'
     - 'r:HKEY_LOCAL_MACHINE\Software\Policies\Skype;'
     - 'p:r:Skype.exe;'
 - id: 10001
   title: "Chat/IM - Yahoo"
   compliance:
    - pci_dss: "10.6.1"
   condition: any
   rules:
     - 'f:\Documents and Settings\All Users\Start Menu\Programs\Yahoo! Messenger;'
     - 'r:HKLM\SOFTWARE\Yahoo;'
 - id: 10002
   title: "Chat/IM ICQ"
   compliance:
    - pci_dss: "10.6.1"
   condition: any
   rules:
     - 'r:HKEY_CURRENT_USER\Software\Mirabilis\ICQ;'
 - id: 10003
   title: "Chat/IM - AOL"
   compliance:
    - pci_dss: "10.6.1"
   references:
    - http://www.aol.com
   condition: any
   rules:
     - 'r:HKEY_LOCAL_MACHINE\SOFTWARE\America Online\AOL Instant Messenger;'
     - 'r:HKEY_CLASSES_ROOT\aim\shell\open\command;'
     - 'r:HKEY_CLASSES_ROOT\AIM.Protocol;'
     - 'r:HKEY_CLASSES_ROOT\MIME\Database\Content Type\application/x-aim;'
     - 'f:\Program Files\AIM95;'
     - 'p:r:aim.exe;'
 - id: 10004
   title: "Chat/IM - MSN"
   references:
    - http://www.msn.com
   condition: any
   rules:
     - 'r:HKEY_LOCAL_MACHINE\SOFTWARE\Microsoft\MSNMessenger;'
     - 'r:HKEY_CURRENT_USER\SOFTWARE\Microsoft\MSNMessenger;'
     - 'f:\Program Files\MSN Messenger;'
     - 'f:\Program Files\Messenger;'
     - 'p:r:msnmsgr.exe;'
 - id: 10005
   title: "Chat/IM - ICQ"
   compliance:
    - pci_dss: "10.6.1"
   references:
    - http://www.icq.com
   condition: any
   rules:
     - 'r:HKLM\SOFTWARE\Mirabilis\ICQ;'
 - id: 10006
   title: "P2P - UTorrent"
   compliance:
    - pci_dss: "10.6.1"
   references:
    - 
   condition: any
   rules:
     - 'p:r:utorrent.exe;'
 - id: 10007
   title: "P2P - LimeWire"
   compliance:
    - pci_dss: "11.4"
   references:
    - 
   condition: any
   rules:
     - 'r:HKEY_LOCAL_MACHINE\SOFTWARE\Limewire;'
     - 'r:HKLM\software\microsoft\windows\currentversion\run -> limeshop;'
     - 'f:\Program Files\limewire;'
     - 'f:\Program Files\limeshop;'
 - id: 10008
   title: "P2P/Adware - Kazaa"
   compliance:
    - pci_dss: "11.4"
   references:
    - 
   condition: any
   rules:
     - 'f:\Program Files\kazaa;'
     - 'f:\Documents and Settings\All Users\Start Menu\Programs\kazaa;'
     - 'f:\Documents and Settings\All Users\DESKTOP\Kazaa Media Desktop.lnk;'
     - 'f:\Documents and Settings\All Users\DESKTOP\Kazaa Promotions.lnk;'
     - 'f:%WINDIR%\System32\Cd_clint.dll;'
     - 'f:%WINDIR%\Sysnative\Cd_clint.dll;'
     - 'r:HKEY_LOCAL_MACHINE\SOFTWARE\KAZAA;'
     - 'r:HKEY_CURRENT_USER\SOFTWARE\KAZAA;'
     - 'r:HKEY_LOCAL_MACHINE\SOFTWARE\MICROSOFT\WINDOWS\CURRENTVERSION\RUN\KAZAA;'
 - id: 10009
   title: "Adware - RxToolBar"
   compliance:
    - pci_dss: "11.4"
   condition: any
   rules:
     - 'r:HKEY_CURRENT_USER\Software\Infotechnics;'
     - 'r:HKEY_CURRENT_USER\Software\Infotechnics\RX Toolbar;'
     - 'r:HKEY_CURRENT_USER\Software\RX Toolbar;'
     - 'r:HKEY_CLASSES_ROOT\BarInfoUrl.TBInfo;'
     - 'r:HKLM\SOFTWARE\Microsoft\Windows\CurrentVersion\Uninstall\RX Toolbar;'
     - 'f:\Program Files\RXToolBar;'
# http://btfaq.com/serve/cache/18.html
 - id: 10010
   title: "P2P - BitTorrent"
   compliance:
    - pci_dss: "10.6.1"
   references:
    - http://btfaq.com/serve/cache/18.html
   condition: any
   rules:
     - 'f:\Program Files\BitTorrent;'
     - 'r:HKEY_CLASSES_ROOT\.torrent;'
     - 'r:HKEY_CLASSES_ROOT\MIME\Database\Content Type\application/x-bittorrent;'
     - 'r:HKEY_CLASSES_ROOT\bittorrent;'
     - 'r:HKLM\Software\Microsoft\Windows\CurrentVersion\Uninstall\BitTorrent;'
# http://www.gotomypc.com
 - id: 10011
   title: "Remote Access - GoToMyPC"
   compliance:
    - pci_dss: "10.6.1"
   references:
    - https://get.gotomypc.com/
   condition: any
   rules:
     - 'f:\Program Files\Citrix\GoToMyPC;'
     - 'f:\Program Files\Citrix\GoToMyPC\g2svc.exe;'
     - 'f:\Program Files\Citrix\GoToMyPC\g2comm.exe;'
     - 'f:\Program Files\expertcity\GoToMyPC;'
     - 'r:HKLM\software\microsoft\windows\currentversion\run -> gotomypc;'
     - 'r:HKEY_LOCAL_MACHINE\software\citrix\gotomypc;'
     - 'r:HKEY_LOCAL_MACHINE\system\currentcontrolset\services\gotomypc;'
     - 'p:r:g2svc.exe;'
     - 'p:r:g2pre.exe;'
 - id: 10012
   title: "Spyware - Twain Tec Spyware"
   compliance:
    - pci_dss: "11.4"
   references:
    - 
   condition: any
   rules:
     - 'r:HKEY_LOCAL_MACHINE\SOFTWARE\Classes\TwaintecDll.TwaintecDllObj.1;'
     - 'r:HKEY_LOCAL_MACHINE\SOFTWARE\twaintech;'
     - 'f:%WINDIR%\twaintec.dll;'
# http://www.symantec.com/security_response/writeup.jsp?docid=2004-062611-4548-99&tabid=2
 - id: 10013
   title: "Spyware - SpyBuddy"
   compliance:
    - pci_dss: "11.4"
   references:
    - http://www.symantec.com/security_response/writeup.jsp?docid=2004-062611-4548-99&tabid=2
   condition: any
   rules:
     - 'f:\Program Files\ExploreAnywhere\SpyBuddy\sb32mon.exe;'
     - 'f:\Program Files\ExploreAnywhere\SpyBuddy;'
     - 'f:\Program Files\ExploreAnywhere;'
     - 'f:%WINDIR%\System32\sysicept.dll;'
     - 'f:%WINDIR%\Sysnative\sysicept.dll;'
     - 'r:HKEY_LOCAL_MACHINE\Software\ExploreAnywhere Software\SpyBuddy;'
 - id: 10014
   title: "Spyware - InternetOptimizer"
   description: "Spyware.SpyBuddy is a commercial keylogger. Its main function is to log keystrokes and information on application use and Internet use on the compromised computer. The spyware can also capture screen shots."
   compliance:
    - pci_dss: "11.4"
   condition: any
   rules:
     - 'r:HKLM\SOFTWARE\Avenue Media;'
     - 'r:HKEY_CLASSES_ROOT\\safesurfinghelper.iebho.1;'
     - 'r:HKEY_CLASSES_ROOT\\safesurfinghelper.iebho;'
